/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.mycompany;

import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author LG
 */
public class NewMemberFrm extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewMemberFrm
     */
    public NewMemberFrm() {
        initComponents();
        initScreen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTeamPnb = new javax.swing.JComboBox<>();
        jSelectBtn = new javax.swing.JButton();
        jUpdateBtn = new javax.swing.JButton();
        jPrintBtn = new javax.swing.JButton();
        jUnMarried = new javax.swing.JRadioButton();
        jMarried = new javax.swing.JRadioButton();
        jMale = new javax.swing.JRadioButton();
        jFeMale = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTbl = new javax.swing.JTable();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        jLabel1.setText("사원번호");

        jMno.setText("jTextField1");

        jLabel2.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        jLabel2.setText("이름");

        jName.setText("jTextField1");

        jLabel3.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        jLabel3.setText("소속 부서");

        jTeamPnb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "총무팀", "인사팀", "개발팀", "사무팀" }));

        jSelectBtn.setText("검색");

        jUpdateBtn.setText("수정");
        jUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateBtnActionPerformed(evt);
            }
        });

        jPrintBtn.setText("인쇄");

        buttonGroup1.add(jUnMarried);
        jUnMarried.setText("미혼");

        buttonGroup1.add(jMarried);
        jMarried.setText("기혼");
        jMarried.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMarriedActionPerformed(evt);
            }
        });

        buttonGroup2.add(jMale);
        jMale.setText("남");
        jMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMaleActionPerformed(evt);
            }
        });

        buttonGroup2.add(jFeMale);
        jFeMale.setText("여");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jUpdateBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPrintBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jName, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jMno, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTeamPnb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jUnMarried)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jMarried)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jMale)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFeMale))
                            .addComponent(jSelectBtn))))
                .addContainerGap(666, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jMno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSelectBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTeamPnb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jUnMarried)
                    .addComponent(jMarried)
                    .addComponent(jMale)
                    .addComponent(jFeMale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jUpdateBtn)
                    .addComponent(jPrintBtn))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTableTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1001", "김도현", "총무팀", null, "기혼", "남"},
                {"1002", "서현교", "사무팀", null, "미혼", "남"},
                {"1003", "이정재", "개발팀", null, "기혼", "남"},
                {"1004", "우수진", "인사팀", null, "미혼", "여"},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "사원번호", "이름", "소속부서", "비고", "결혼여부", "성별"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableTbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTblMouseClicked
        int selectedRow = jTableTbl.getSelectedRow();
        if(selectedRow < 0){
            return;
        }
        Vector vt = (Vector)
                ((DefaultTableModel)jTableTbl.getModel()).getDataVector().elementAt(selectedRow);
        
        this.jMno.setText((String)vt.get(0));
        this.jName.setText((String)vt.get(1));
        this.jTeamPnb.getModel().setSelectedItem((String)vt.get(2));
        
        String married = (String)vt.get(4);
        String gender = (String)vt.get(5);
        if(married.compareTo("기혼")==0){
            jMarried.setSelected(true);
        }
        else{
            jUnMarried.setSelected(true);
        }
        if(gender.compareTo("남")==0){
            jMale.setSelected(true);
        }
        else{
            jFeMale.setSelected(true);
        }
        
        
    }//GEN-LAST:event_jTableTblMouseClicked

    private void jUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateBtnActionPerformed
        int selectedRow = jTableTbl.getSelectedRow();
        if(selectedRow < 0){
            return;
        }
        
        String idNum = this.jMno.getText();
        String name = this.jName.getText();
        String team = (String)this.jTeamPnb.getSelectedItem();
        String married = "기혼";
        String gender = "남";
        resultModel.setValueAt(idNum, selectedRow, 0);
        resultModel.setValueAt(name, selectedRow, 1);
        resultModel.setValueAt(team, selectedRow, 2);
        
        if(jMarried.isSelected()){
            married = "기혼";
        }
        else{
            married = "미혼";
        }
        if(jMale.isSelected()){
            gender = "남";
        }
        else{
            gender = "여";
        }
        resultModel.setValueAt(married, selectedRow, 4);
        resultModel.setValueAt(gender, selectedRow, 5);

        
        
       

    }//GEN-LAST:event_jUpdateBtnActionPerformed

    private void jMarriedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMarriedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMarriedActionPerformed

    private void jMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMaleActionPerformed
    DefaultTableModel resultModel;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton jFeMale;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jMale;
    private javax.swing.JRadioButton jMarried;
    private javax.swing.JTextField jMno;
    private javax.swing.JTextField jName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jPrintBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jSelectBtn;
    private javax.swing.JTable jTableTbl;
    private javax.swing.JComboBox<String> jTeamPnb;
    private javax.swing.JRadioButton jUnMarried;
    private javax.swing.JButton jUpdateBtn;
    // End of variables declaration//GEN-END:variables

    private void initScreen() {
        resultModel = ((DefaultTableModel)jTableTbl.getModel());
        TableColumnModel columnModel = jTableTbl.getColumnModel();
        columnModel.getColumn(3).setMinWidth(0);
        columnModel.getColumn(3).setMaxWidth(0);
        columnModel.getColumn(3).setPreferredWidth(0);
    }
}
